import { webcontentObjectType } from 'samples/webcontentObjectType.ts';
import { mainCommonsWebcontentType } from 'samples/mainCommonsWebcontentType.ts';

export type profilepageWebcontentType = {
  commons: mainCommonsWebcontentType;
  page: {
    title: webcontentObjectType;
    informations: webcontentObjectType;
    usernameTitle: webcontentObjectType;
    emailTitle: webcontentObjectType;
    emailDisplayTitle: webcontentObjectType;
    yes: webcontentObjectType;
    no: webcontentObjectType;
    passwordTitle: webcontentObjectType;
    passwordPlaceholder: webcontentObjectType;
    pronounsTitle: webcontentObjectType;
    unknown: webcontentObjectType;
    descriptionTitle: webcontentObjectType;
    descriptionPlaceholder: webcontentObjectType;
    profilePictureTitle: webcontentObjectType;
    otherOptions: webcontentObjectType;
    displayTheme: webcontentObjectType;
    lightMode: webcontentObjectType;
    language: webcontentObjectType;
    french: webcontentObjectType;
    displayedNameTitle: webcontentObjectType;
    tagsButton: webcontentObjectType;
    favouriteButton: webcontentObjectType;
    disconnectButton: webcontentObjectType;
    returnButton: webcontentObjectType;
    descriptionEditTitle: webcontentObjectType;
    descriptionContent: webcontentObjectType;
    descriptionContentPlaceholder: webcontentObjectType;
    displayedNameEditTitle: webcontentObjectType;
    displayedNameContent: webcontentObjectType;
    displayedNameContentPlaceholder: webcontentObjectType;
    pronounsEditTitle: webcontentObjectType;
    pronounsContent: webcontentObjectType;
    pronounsContentPlaceholder: webcontentObjectType;
    emailDisplayConfirmationTitle: webcontentObjectType;
    emailDisplayConfirmationContent: webcontentObjectType;
    passwordEditTitle: webcontentObjectType;
    passwordContent: webcontentObjectType;
    checkerContent: webcontentObjectType;
    warningMessage: webcontentObjectType;
    tagNumberDisclaimer: webcontentObjectType;
    profilePictureEditTitle: webcontentObjectType;
    profilePictureEditContent: webcontentObjectType;
  };
};
